name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material==9.0.0b4
      
      - name: Install Python dependencies
        run: |
          pip install \
            "cairosvg>=2.5" \
            "mkdocs-git-committers-plugin-2>=1.1.1" \
            "mkdocs-git-revision-date-localized-plugin>=1.0" \
            "mkdocs-minify-plugin>=0.3" \
            "mkdocs-rss-plugin>=1.2" \
            "mkdocs-redirects>=1.0" \
            "pillow<10" \
            "mkdocs-glightbox"
      
      - run: mkdocs gh-deploy --force
